tasks:
  - name: Clippy
    init: --tests --all-targets --all-features -- -D warnings
  - name: Testing
    init: cargo test -vv --features async-std-runtime
  - name: Build
    init: cargo build --all-features
github:
  prebuilds:
    branches: true
    pullRequestsFromForks: true
    addBadge: true
vscode:
  extensions:
    - swellaby.vscode-rust-test-adapter
    - serayuzgur.crates
    - belfz.search-crates-io
    - bungcip.better-toml
